server:
  port: 8085

spring:
  application:
    name: my-cars
  datasource:
    url: jdbc:h2:mem:test
    initialization-mode: always
    hikari:
      maximum-pool-size: 30
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000 
  jpa: 
    properties: 
      hibernate: 
        id: 
          new_generator_mappings: false
        format_sql: true
        jdbc: 
          lob: 
            non_contextual_creation: true
        ddl-auto: update
        type: trace
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jackson:
    default-property-inclusion: NON_NULL

security:
  oauth2:
    client:
      access-token-validity-seconds: 1800
      authorized-grant-types: password,refresh_token
      client-id: tomwellApp
      client-secret: $2a$10$zX8v86SyTpSivZWdCO9yqu9ccAK5nb5xs9Fa2xaj7F0Ecjn9jr0JC
      resource-ids: resource_id
      scope: read,write
    resource: 
      filter-order: 3

logging: 
  level: 
    org: 
      hibernate: 
        SQL: DEBUG
      type: 
        descriptor: 
        sql: 
          BasicBinder: TRACE